services:
  dev-server:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./dev-server/Dockerfile
    volumes:
      - ./dev-server:/app
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    networks:
      - portfolio-network

  vue-server:
    profiles:
      - vue
    build:
      context: .
      dockerfile: ./vue-server/Dockerfile
    ports:
      - 8080:8080
    networks:
      - portfolio-network

  openvpn-server:
    profiles:
      - openvpn
    build:
      context: openvpn-server


networks:
  portfolio-network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: "10.0.2.1"
