services:
  dev-server:
    build:
      context: .
      dockerfile: ./dev-server/Dockerfile
    volumes:
      - type: bind
        source: ./ssh
        target: /ssh
        read_only: true
    ports:
      - "3333:3333"
      - "80:80"
      - "443:443"
      - "2222:22"
      - "1194:1194"
    networks:
      docker-vpn:
        ipv4_address: 10.0.2.30
  vue-server:
    build:
      context: .
      dockerfile: ./vue-server/Dockerfile
    volumes:
      - type: bind
        source: ./ssh
        target: /ssh
        read_only: true
    ports:
      - "443:443"
      - "80:80"
      - "3333:3333"
      - "1194:1194"
    networks:
      docker-vpn:
        ipv4_address: 10.0.2.20

  # openvpn-server:
  #   build:
  #     context: openvpn-server
  #   ports:
  #     - "1194:1194"
  #   networks:
  #     docker-vpn:
  #       ipv4_address: 10.0.2.10

networks:
  docker-vpn:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: "10.0.2.1"
