services:
  dev-server:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./dev-server/Dockerfile
    volumes:
      - ./dev-server:/app
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    networks:
      - portfolio-network

  vue-server:
    profiles:
      - vue
    build:
      context: .
      dockerfile: ./vue-server/Dockerfile
    volumes:
      - type: bind
        source: ./ssh
        target: /ssh
        read_only: true
    ports:
      - 443:443
      - 80:80
      - 8080:8080
      - 2222:22
      - 3333:3000
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: "10.0.2.1"
